-- MySQL Script generated by MySQL Workbench
-- Fri Jun 11 21:02:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDgestiondocumental
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BDgestiondocumental` ;

-- -----------------------------------------------------
-- Schema BDgestiondocumental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDgestiondocumental` DEFAULT CHARACTER SET utf8 ;
USE `BDgestiondocumental` ;

-- -----------------------------------------------------
-- Table `BDgestiondocumental`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDgestiondocumental`.`Rol` (
  `idRol` INT(10) NOT NULL,
  `nombre_Rol` VARCHAR(30) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDgestiondocumental`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDgestiondocumental`.`Usuario` (
  `idUsuario` INT(10) NOT NULL,
  `documento_Identidad` INT(10) NOT NULL,
  `Nombre` VARCHAR(50) NULL,
  `Dirección` VARCHAR(45) NULL,
  `Telefono` INT(10) NULL,
  `correo_electrónico` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `documento_Identidad_UNIQUE` (`documento_Identidad` ASC) VISIBLE,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idRol`
    FOREIGN KEY ()
    REFERENCES `BDgestiondocumental`.`Rol` ()
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDgestiondocumental`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDgestiondocumental`.`Cargo` (
  `idCargo` INT(10) NOT NULL,
  `nombre_Cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idCargo`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY ()
    REFERENCES `BDgestiondocumental`.`Usuario` ()
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDgestiondocumental`.`tipo_Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDgestiondocumental`.`tipo_Documento` (
  `idtipo_Documento` INT(10) NOT NULL,
  `tipo_Documento` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_Documento`),
  UNIQUE INDEX `idtipo_Documento_UNIQUE` (`idtipo_Documento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDgestiondocumental`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDgestiondocumental`.`Documento` (
  `idDocumento` INT(10) NOT NULL,
  `Asunto` VARCHAR(45) NULL,
  `Encabezado` VARCHAR(45) NULL,
  `contenido_Documento` VARCHAR(100) NULL,
  `fecha_Creación` DATETIME NULL,
  `firma` VARCHAR(25) NULL,
  `Foliatura` VARCHAR(45) NULL,
  `logo_Entidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocumento`),
  UNIQUE INDEX `idDocumento_UNIQUE` (`idDocumento` ASC) VISIBLE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY ()
    REFERENCES `BDgestiondocumental`.`Usuario` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtipo_Documento`
    FOREIGN KEY ()
    REFERENCES `BDgestiondocumental`.`tipo_Documento` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDgestiondocumental`.`Contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDgestiondocumental`.`Contratos` (
  `idContrato` INT(10) NOT NULL,
  `nombre_Contrato` VARCHAR(45) NULL,
  `nit_Hospital` INT(10) NULL,
  `marco_legal_Disponible` VARCHAR(45) NULL,
  `cláúsulas` VARCHAR(45) NULL,
  `reglamento_Hospital` VARCHAR(45) NULL,
  `Actividades` VARCHAR(50) NULL,
  `area_Trabajo` VARCHAR(45) NULL,
  `salario` INT(10) NULL,
  `periodo_Pago` VARCHAR(45) NULL,
  `fecha_Inicio` DATETIME NULL,
  `fecha_final` DATETIME NULL,
  PRIMARY KEY (`idContrato`),
  UNIQUE INDEX `nit_Hospital_UNIQUE` (`nit_Hospital` ASC) VISIBLE,
  UNIQUE INDEX `idContrato_UNIQUE` (`idContrato` ASC) VISIBLE,
  CONSTRAINT `idtipo_Documento`
    FOREIGN KEY ()
    REFERENCES `BDgestiondocumental`.`tipo_Documento` ()
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDgestiondocumental`.`tipo_Contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDgestiondocumental`.`tipo_Contratos` (
  `idtipo_Contrato` INT(10) NOT NULL,
  `tipo_Contrato` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_Contrato`),
  UNIQUE INDEX `idtipo_Contrato_UNIQUE` (`idtipo_Contrato` ASC) VISIBLE,
  CONSTRAINT `idContrato`
    FOREIGN KEY ()
    REFERENCES `BDgestiondocumental`.`Contratos` ()
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDgestiondocumental`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDgestiondocumental`.`Persona` (
  `idPersona` INT(10) NOT NULL,
  `documento_Identidad` INT(10) NULL,
  `Nombre` VARCHAR(50) NULL,
  `Apellido` VARCHAR(50) NULL,
  `Dirección` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `correo_Electronico` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `documento_Identidad_UNIQUE` (`documento_Identidad` ASC) VISIBLE,
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `idContrato`
    FOREIGN KEY ()
    REFERENCES `BDgestiondocumental`.`Contratos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDgestiondocumental`.`Supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDgestiondocumental`.`Supervisor` (
  `idSupervisor` INT(10) NOT NULL,
  `documento_identidad` INT(10) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NULL,
  `Telefono` INT(10) NULL,
  `correo_Electronico` VARCHAR(45) NULL,
  PRIMARY KEY (`idSupervisor`),
  UNIQUE INDEX `documento_identidad_UNIQUE` (`documento_identidad` ASC) VISIBLE,
  CONSTRAINT `idContrato`
    FOREIGN KEY ()
    REFERENCES `BDgestiondocumental`.`Contratos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
